apiVersion: v1
kind: Secret
metadata:
  name: csi-s3-secret
  namespace: kube-system
stringData:
  accessKeyID: YCAJEYKdlsvFUcYku7-W3E6Y-
  secretAccessKey: YCPXlyKBRmcOeBcCP3iUn4qAVbAhEXzd9WQwROhv
  endpoint: https://storage.yandexcloud.net
