apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: otus-store
  namespace: vault
spec:
  retrySettings:
    maxRetries: 5
    retryInterval: "10s"
  
  provider:
    vault:
      server: "http://vault.vault:8200"
      # Path is the mount path of the Vault KV backend endpoint
      path: "otus"
      # Version is the Vault KV secret engine version.
      # This can be either "v1" or "v2", defaults to "v2"
      version: "v2"
      # vault enterprise namespace: https://www.vaultproject.io/docs/enterprise/namespaces
      namespace: "vault"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "otus"
          # Optional service account reference
          serviceAccountRef:
            name: "vault-auth"
          # namespace: "vault"
          # Optional secret field containing a Kubernetes ServiceAccount JWT
          # used for authenticating with Vault
          #secretRef:
          #  name: "my-secret"
          #  namespace: "secret-admin"
          #  key: "vault"

