apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: k8s-web-pvc
  namespace: homework
  labels:
    app: k8s-web
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: "k8s-web-pvc-sc"
