apiVersion: v1
kind: Service
metadata:
  name: k8s-web-svc
  namespace: homework
spec:
  selector:
    app: k8s-web
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8000
